app/auth.py
from flask import Blueprint, redirect, url_for, render_template, request, flash, jsonify
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from app import db
import json

from .models import Trainer, Trainee, Gig


auth = Blueprint('auth', __name__)


@auth.route('/trainer/signup', methods=['GET', 'POST'])
def trainer_signup():

    data = request.json

    email = data['email']
    username = data['username']
    phone_number = data['phone_number']
    password = data['password']

    # Lookup if email or username exists
    user_email = Trainer.query.filter_by(email=email).first()
    user_username = Trainer.query.filter_by(username=username).first()

    if user_email:
        return jsonify({'message': 'Email already exists', 'status': 'error'})
    if user_username:
        return jsonify({'message': 'Username already taken', 'status': 'error'})

    trainer = Trainer(email=email, username=username, password=generate_password_hash(
        password), phone_number=phone_number, urole='TRAINER')

    db.session.add(trainer)
    db.session.commit()

    return jsonify({'message': 'Trainer created', 'status': 'success'})


@auth.route('/trainer/login', methods=['POST'])
def trainer_login():
    data = request.json

    username = data['username']
    password = data['password']

    trainer = Trainer.query.filter_by(username=username).first()

    if not trainer:
        return jsonify({'message': 'No such user', 'status': 'error'})
    if not check_password_hash(trainer.password, password):
        return jsonify({'message': 'Wrong password', 'status': 'error'})

    # if the above check passes then...
    login_user(trainer)
    user_id = current_user.id
    return jsonify({'message': 'Logged in', 'status': 'success', 'user_id': user_id})


@auth.route('/trainee/signup', methods=['POST'])
def trainee_signup():
    data = request.json

    email = data['email']
    username = data['username']
    password = data['password']

    # Lookup if email or username exists
    user_email = Trainee.query.filter_by(email=email).first()
    user_username = Trainee.query.filter_by(username=username).first()

    if user_email:
        return jsonify({'message': 'Email already exists', 'status': 'error'})
    if user_username:
        return jsonify({'message': 'Username already taken', 'status': 'error'})

    trainee = Trainee(email=email, username=username, password=generate_password_hash(
        password), urole='TRAINEE')

    db.session.add(trainee)
    db.session.commit()

    return jsonify({'message': 'Trainee created', 'status': 'success'})


@auth.route('/trainee/login', methods=['POST'])
def trainee_login():
    data = request.json

    username = data['username']
    password = data['password']

    trainee = Trainee.query.filter_by(username=username).first()

    if not trainee:
        print('Trainee with that username does not exist')
        return jsonify({'message': 'Trainee with that username does not exist', 'status': 'error'})
    if not check_password_hash(trainee.password, password):
        print('Incorect password.')
        return jsonify({'message': 'Incorect password.', 'status': 'error'})

    # if the above check passes then...
    login_user(trainee)

    return jsonify({'message': 'Trainee logged in', 'status': 'success', })


@auth.route('/logout')
@login_required
def logout():
    logout_user()

    return redirect(url_for('main.index'))

app/main.py
import json
from flask import Blueprint, flash, redirect, render_template, url_for, request, jsonify
from flask_login import current_user, login_user, logout_user, login_required


from app import app, db
from .models import Trainer, Trainee, Gig, Enroll, GigSchema


import requests
import random


main = Blueprint('main', __name__)


weather = {
    "data": [
        {
            "day": "1/6/2019",
            "temperature": "23",
            "windspeed": "16",
            "event": "Sunny"
        },

    ]}


@main.route('/', methods=['GET'])
def index():
    gigs = Gig.query.all()

    gigs_schema = GigSchema(many=True)

    return jsonify(gigs_schema.dump(gigs))


@main.route('/weatherReport/')
def WeatherReport():
    global weather
    return jsonify([weather])


@main.route('/create_gig', methods=['POST'])
def create_gig():

    data = request.json

    title = data['title']
    price = data['price']
    duration = data['duration']
    category = data['category']
    trainer_id = data['trainerId']

    gig = Gig(title=title, price=price, duration=duration,
              category=category, trainer_id=trainer_id)

    db.session.add(gig)
    db.session.commit()

    return jsonify({'message': 'Gig created', 'status': 'success'})


@main.route('/book_gig/<gig_id>', methods=['GET', 'POST'])
@login_required
def book_gig(gig_id):

    if current_user.urole != "TRAINEE":
        flash('You are not authorized to book a gig')
        return redirect(url_for('main.index'))

    gig = Gig.query.filter_by(id=gig_id).first()

    if not gig:
        flash('Gig not found')
        return redirect(url_for('main.index'))

    # check if the user has already booked the gig
    if current_user.id in [enroll.trainee_id for enroll in gig.enrolls]:
        flash('You have already booked this gig')
        return redirect(url_for('main.index'))

    enroll = Enroll(gig_id=gig.id, trainee_id=current_user.id)

    db.session.add(enroll)
    db.session.commit()
    print(gig.enrolls)

    return redirect(url_for("main.index"))


@main.route('/display-gig/<gig_id>', methods=['GET'])
def display_gig(gig_id):

    gig = Gig.query.filter_by(id=gig_id).first()
    gig_category = gig.category

    url = f"https://exercisedb.p.rapidapi.com/exercises/bodyPart/{gig_category}"

    headers = {
        'x-rapidapi-host': "exercisedb.p.rapidapi.com",
        'x-rapidapi-key': "f50615db51msh1895e876776f30ep1045d3jsn5d2af3e0380f"
    }

    response = requests.request("GET", url, headers=headers)
    random_index = random.randint(0, 10)
    dis_gig = response.json()[random_index]

    return jsonify(dis_gig)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block navbar %} {% include 'navbar.html' %} {% endblock %} {% block
    content %} {% endblock %}
  </body>
</html>

app/templates/index.html
{% extends 'base.html' %}


{% import "macros.html" as macro with context %}

{% block content %}


<aside class="sidebar">
    {% include 'sidebar.html' %}
</aside>

<section class="content">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="notification is-danger">
        {{ messages[0] }}
    </div>
    {% endif %}
    {% endwith %}


    {% for gig in gigs %}


    <div class="gig {{className}} ">


        <p> {{gig.title}} </p>
        <p> {{gig.price}} </p>
        <p> {{gig.category}} </p>

        {% if current_user.urole=='TRAINEE'%}
        <a href="{{url_for('main.book_gig', gig_id=gig.id)}}  ">Book Gig</a>


        {% for enroll in gig.enrolls %}
        {% if enroll.trainee_id == current_user.id %}
        <p class="active-gig"> You are enrolled </p>
        {% endif %}
        {% endfor %}

        <br>

        <a href="{{url_for('main.view_gig', gig_id=gig.id)}}  ">View Gig</a>
        {% endif %}


    </div>

    <hr>


    {% endfor %}

</section>

<aside class="quote">


</aside>


{% endblock %}

app/templates/macros.html
{% macro displayBlogs(gigs) %}

<div class="posts">
    {{ gigs|length }}

    {% for blog in gigs %}


    <div class="post">

        <div class="post-info">

            <div class="post__header">
                <span class="post__author">@{{blog.user.username}} </span>
                <span class="post__date">{{blog.date_posted.strftime('%b %d')}}
                </span>


            </div>
            <a href="{{url_for('main.blog', blog_id=blog.id)}} ">
                <h3 class="post__title">{{blog.title}} </h3>
                <p class="post__content">
                    {{blog.content}}
                </p>
            </a>


            <div class="post__footer">
                <a href="{{ url_for('main.category', category=blog.category) }} "
                    class="post__category">#{{blog.category}} </a>

            </div>


        </div>

    </div>

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">keep FIt</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <ul class="nav navbar-nav">
          <li><a href="#">About Us</a></li>
          <ul class="nav navbar-nav">
            <li><a href="#" >Services</a>
            </li>
            <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
              <li><a href="#">Profile</a></li>         
              <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
              {% if user.urole=='Trainer' %}
               <li><button class="btn btn-secondary" type="button" style=" margin-top: 10px;">Create gig</button></li>
               {% endif %}
               {% else %} 
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                 style="margin-left: 450px; margin-top: 10px;">
                  Sign in
                </button>
                {% endif %}
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                 <li> <a class="dropdown-item" href=" {{url_for('auth.login')}} "> As Trainer</a></li>
                 <li> <a class="dropdown-item" href=" {{url_for('auth.login_trainee')}} ">As Trainee</a></li>
                </div>
              </div>
          
            </ul>
          </div>
        </div>
      </div>

app/templates/sidebar.html
<div class="hashtags">
    <h4 class="sidebar__title">
        Categories
    </h4>
    {% for blog in blogs %}
    <a href="/category/{{blog.category}}" class="hashtag">
        #{{blog.category}}
    </a>
    {% endfor %}


</div>


{% if current_user.is_authenticated %}
{% if page=='profile' %}
<div class="profile-image">
    <img src="../static/img/{{current_user.profile_pic}}" alt="Profile Img"
        class="user-profile__img">

    <a href="{{url_for('main.upload_profile_pic')}} ">
        <img src="{{url_for('static', filename='img/edit-pen.svg')}} " alt="Edit"
            class="edit-icon--profile__img">
    </a>
</div>

{% endif%}


<a href="{{ url_for('auth.logout') }}" class="logout btn">
    <img src="{{ url_for('static', filename='img/logout.svg') }}" class="logout-icon v">
    Logout
</a>

{% endif %}

app/templates/trainee.html
<html>
    <h3>Welcome Trainee To your page</h3>
</html>

app/templates/trainer.html
<html>
    Hey Trainer this is your Page
</html>

app/templates/view_gig.html
{% extends 'base.html' %}


{% import "macros.html" as macro with context %}

{% block content %}


<aside class="sidebar">
    {% include 'sidebar.html' %}
</aside>

<section class="content">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="notification is-danger">
        {{ messages[0] }}
    </div>
    {% endif %}
    {% endwith %}


    <img src="{{dis_gig.gifUrl}} " alt="">


</section>

<aside class="quote">


</aside>


{% endblock %}